version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      # NOTE: Workaround to fix issue where composite actions
      # are not bumped automatically. Glob expression DOES NOT
      # work so they have to be defined explicitly.
      # https://github.com/dependabot/dependabot-core/issues/6704
      - "/setup-kicad"
      - "/setup-zephyr-sdk"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "Asia/Singapore"
    groups:
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
