name: Set up KiCad
description: |
  Installs KiCad to the runner environment.

  For more information, see: https://www.kicad.org

inputs:
  # TODO: Not all versions are in the PPA, consider building from source!
  version:
    description: Release version of KiCad to be installed

runs:
  using: "composite"

  steps:
    # TODO: Support other distros and OS?
    - name: Add KiCad Ubuntu PPA
      shell: bash
      run: |
        sudo add-apt-repository ppa:kicad/kicad-8.0-releases

    - name: Determine latest version
      id: kicad-version
      shell: bash
      run: |
        apt-cache policy kicad
        apt-cache madison kicad
        echo "latest=$(apt-cache policy kicad | awk '/Candidate:/ {print $2}')" >> "${GITHUB_OUTPUT}"

    - name: Install KiCad
      shell: bash
      run: |
        sudo apt-get install "kicad=${{ inputs.version || steps.kicad-version.outputs.latest }}"
        kicad-cli --version
