name: setup-kicad
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-exact-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "8.0.6"
          - "8.0.5"

    steps:
      - name: Checkout branch
        uses: actions/checkout@v5.0.0

      - name: Run action with exact version
        uses: ./setup-kicad
        with:
          version: ${{ matrix.version }}

      - name: Verify KiCad installation
        run: |
          kicad-cli --version
          which kicad
          which kicad-cli

  test-ppa-fallback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v5.0.0

      - name: Run action without version (PPA fallback)
        uses: ./setup-kicad

      - name: Verify KiCad installation
        run: |
          kicad-cli --version
          which kicad
          which kicad-cli
