name: setup-zephyr-sdk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Run action
        uses: ./setup-zephyr-sdk
        with:
          version: "1.0.1"
          toolchains: arm-zephyr-eabi

      - name: Verify installation
        shell: bash
        run: |
          "${ZEPHYR_SDK_INSTALL_DIR}/gnu/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc" --version
