name: setup-kicad-library-utils

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-default:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v5.0.0

      - name: Run action (default version)
        uses: ./setup-kicad-library-utils

      - name: Verify installation
        shell: bash
        run: |
          klc-footprint --help
          klc-symbol --help

  test-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v5.0.0

      - name: Run action (with v8 version)
        uses: ./setup-kicad-library-utils
        with:
          version: v8

      - name: Verify installation
        shell: bash
        run: |
          klc-footprint --help
          klc-symbol --help
