name: setup-zephyr-sdk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run action
        uses: ./setup-zephyr-sdk
        with:
          version: "0.16.5-1"
          toolchains: arm-zephyr-eabi
