name: setup-kicad
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-source-build:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # Building from source takes time

    steps:
      - name: Checkout branch
        uses: actions/checkout@v5.0.0

      - name: Run action with specific version
        uses: ./setup-kicad
        with:
          version: "8.0.6"

      - name: Verify KiCad installation
        run: |
          kicad-cli --version
          which kicad
          which kicad-cli
